import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'
import { VitePWA } from 'vite-plugin-pwa'

// The product name is defined ONCE (src/config/brand.js) and derived everywhere. Do not re-type
// a name literal in this file — the manifest and the index.html <title> below are two of the
// surfaces that drifted apart before. See brand.js and config/__tests__/brand.test.js.
import { PRODUCT_NAME, SHORT_NAME, DESCRIPTION } from './src/config/brand.js'

/**
 * Substitutes %PRODUCT_NAME% in index.html, so the pre-hydration <title> derives from brand.js
 * like every other surface. Vite's built-in HTML interpolation only reaches `%VITE_*%` env vars,
 * which is why this needs a hook. Applies in dev and in build.
 */
const productNameHtml = {
  name: 'product-name-html',
  transformIndexHtml(html) {
    return html.replaceAll('%PRODUCT_NAME%', PRODUCT_NAME)
  },
}

// https://vitejs.dev/config/
export default defineConfig({
  plugins: [
    react(),
    productNameHtml,
    VitePWA({
      registerType: 'autoUpdate',
      includeAssets: ['favicon.ico', 'apple-touch-icon.png', 'mask-icon.svg'],
      workbox: {
        // Default globPatterns omits .webp — mascot images would be excluded from
        // the SW precache and fetched cold on every first load, causing broken-icon
        // flashes on slow networks. Explicitly include webp here.
        //
        // woff2 likewise: the fonts are self-hosted and bundled (no CDN), but omitting
        // them from the precache meant an offline first load fell back to system fonts,
        // losing the Baloo 2 / Nunito type identity exactly when connectivity is worst.
        // Confirmed still open by the 2026-08-15 network audit.
        //
        // Scoped to the LATIN subsets on purpose: PRECACHED SUBSETS TRACK RENDERED SCRIPTS.
        // Fontsource ships each family split by unicode-range (latin, latin-ext, cyrillic,
        // vietnamese, devanagari), and the browser only FETCHES the ranges a page actually
        // uses — but precaching is indiscriminate, so an unscoped `woff2` glob downloads all
        // nine on install (~316 kB) to render ~72 kB of Latin. We render no Devanagari,
        // Cyrillic or Vietnamese today. Revisit this line if UI localisation ships — the
        // subsets precached must then follow the scripts actually rendered.
        globPatterns: ['**/*.{js,css,html,ico,png,svg,webp}', '**/*-latin-wght-normal-*.woff2'],

        // /privacy.html is a REAL page, not an SPA route. Without this the service worker's
        // navigation fallback (`createHandlerBoundToURL('index.html')`) answers every
        // navigation with the app shell — so a Play reviewer or a parent opening the policy
        // link on a device with the SW installed would get the app instead of the policy.
        // The page is generated by scripts/build-privacy-page.mjs into public/, so it IS
        // precached and stays available offline; this only stops the fallback from eating it.
        navigateFallbackDenylist: [/^\/privacy\.html$/],
      },
      manifest: {
        name: PRODUCT_NAME,
        short_name: SHORT_NAME,
        description: DESCRIPTION,
        theme_color: '#ffffff',
        icons: [
          {
            src: '/pwa-192x192.png',
            sizes: '192x192',
            type: 'image/png'
          },
          {
            src: '/pwa-512x512.png',
            sizes: '512x512',
            type: 'image/png'
          }
        ]
      }
    })
  ],
})
